version: "3.9"

services:
  api:
    build: .
    container_name: healthcare-readmission-api
    ports:
      - "8000:8000"
    environment:
      MODEL_PATH: /app/models/readmission_model.joblib
      DATABASE_URL: postgresql+psycopg2://postgres:postgres@postgres:5432/claims_db
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    container_name: healthcare-claims-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: claims_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
